### PR TITLE
Arguably better update script

### PR DESCRIPTION
**Pull request by Diatrus**

### CODE REVIEW

**Comment by debouncedgit** [comment]
The function of finding & installing the dependency needed doesn't seem to be working on WSL. Will continue to test on other operating systems. Furthermore, after our discussion regarding GPG support, it is available with WSL, did further testing regarding that aswell. (gnupg)

**Review by lafi8877 — APPROVED** [review]

**Review by lafi8877 — APPROVED** [review]

**Comment by ugcgt** [comment]
__

**Review by ugcgt — COMMENTED** [review]
F

**Comment by ugcgt** [comment]
__

**Pull request closed without merging**
